const portfolioData = {
  HomePage: {
    id: 0,
    keywords: {
      hero_img: "./assets/home_img.png",
      hero_upper_text: "Hi There,",
      hero_mid_text: "This is Nitesh Yadav.",
      profession_line: "I am Full-Stack Web Developer",
      tag_line: "I convert the imagination into a creative product.",
    },
  },
  ProjectPage: {
    id: 1,
    keywords: {
      heading: "PROJECTS",
      card_1st_link: "View Code",
      card_2nd_link: "Deploy",
    },
    project_data: [
      {
        id: 0,
        rank: 1,
        active: 1,
        gitHubLink: "https://github.com/mrRhenium/tournamentOrganiser",
        siteLink: "https://mrrhenium.github.io/tournamentOrganiser/",
        titleImg: "./assets/project/trtmt_logo.png",
        title: "Tournament Organiser App",
        subTitle: "- It is based on my Real Problem.",
        descriptionImg: "./assets/project/trtmt_site.png",
        description: `PROBLEM : When we used to play badminton like sports with my friends. We were facing the problem😢 of fixing the accurate matches among the multiple players, remembering each player's match record & profiles and it also very time consuming process. But after this Web Application we resolve all problems.😎`,
        points: [
          "Eye Catching UI is implement.",
          "User's can send their Feedback.",
          "Firebase database is used to stored the user's feedback.",
          "Local Storage is used to store the app related data.",
          "Optimized Algorithms are use to decide matches.",
          "Randome Matches is organise among the players.",
          "At the end of Tournament Winners are listed on the Leaderboard.",
          "Rematch functioy is avalaible.",
          "Match Timing is also Recorded.",
        ],
        techUsed: [
          "Firebase",
          "JavaScript",
          "CSS",
          "HTML",
          "Figma",
          "JS API's",
        ],
      },
      {
        id: 1,
        rank: 2,
        active: 1,
        gitHubLink: "https://github.com/mrRhenium/Weather-75",
        siteLink: "https://mrrhenium.github.io/Weather-75/",
        titleImg: "./assets/project/weather_logo.png",
        title: "Weather Report Web-App.",
        subTitle: `- It is based on "How to use API's".`,
        descriptionImg: "./assets/project/weather_site.png",
        description: `It is the Web-Application based on "How to use API's". It is use to search weather report of any city in the world. we are using the API's for generating the Weather information.
      AI is use for Voice Synthesis who tell us the weather info., Let's Check-Out.`,
        points: [
          "Run on any device : Full Responsive.",
          "API's is Used to build the application.",
          "Voice's search Functionality is implemented.",
          "We can also Hear the information -> AI is use for Voice Synthesis.",
          "User's can give feedback to us.",
          "Firebase is used to store the data.",
          "Best UI/UX created : Attractive animation is used.",
        ],
        techUsed: ["JavaScript", "CSS", "HTML", "Firbase", "JS API's"],
      },
      {
        id: 2,
        rank: 3,
        active: 1,
        gitHubLink: "https://github.com/mrRhenium/ImagesUpload",
        siteLink: "https://github.com/mrRhenium/ImagesUpload",
        titleImg: "./assets/project/dualSvr_logo.png",
        title: "Working with Dual Server.",
        subTitle: "- This type of project nowhere on Internet.",
        descriptionImg: "./assets/project/dualSvr_site.png",
        description: `PROBLEM : Whenever we create any Text-Image uploading app like Instagram and other Social Media like applications. It usually contain huge data and images which increase the load on server, through it server become slow and heavy. For overcome these type of situatiosn, they are using more than one server.`,
        points: [
          "Get, Post, Update, Delete with data (Text-Image) functionality is implemented.",
          "CORS (Cross Origin Resource Sharing) is implemented in it.",
          "Fully Backend Project.",
          "Have Dual Server (Main-Server & Media-Server).",
          "Primary Server is used for text related data and Media Server is used for Images.",
          "Fs, CORS & Multer Module is used in it.",
          "Self-Made project: Not found on Internet.",
        ],
        techUsed: ["Node-Js", "Express", "MongoDB", "NPM Packages", "HTML"],
      },
      {
        id: 3,
        rank: 4,
        active: 1,
        gitHubLink: "https://myportfolio-0.1-version.netlify.app/",
        siteLink: "https://github.com/mrRhenium/myPortfolio",
        titleImg: "./assets/project/portfolio_logo.png",
        title: "My Portfolio.",
        subTitle: "- Best UI/UX project",
        descriptionImg: "./assets/project/portfolio_site.png",
        description: `You already know about this project which you are seeing here is my Portfolio. This is frontent + Database related project. Whole Data which you are seeing is fetch from the Database and rendering on you Browser. Animation is used on Every Page.`,
        points: [
          "It is React-Js based Frontent + Database Project.",
          "Intersection & Resize Observer (JS-API's) is Used in it.",
          "Menu Icons dynamically change on Scrolling.",
          "Slide-Show function is implemented in it.",
          "Feedback and Rate-Us funtionality in it.",
          "Less write and Do more : This project is perfect example of it.",
        ],
        techUsed: ["React-Js", "Firebase", "HTML", "CSS", "JS-API's"],
      },
    ],
  },
  skillPage: {
    id: 2,
    keywords: {
      heading: "Skills",
    },
    category: [
      {
        id: 0,
        name: "all",
      },
      {
        id: 1,
        name: "frontend",
      },
      {
        id: 2,
        name: "backend",
      },
      {
        id: 3,
        name: "database",
      },
      {
        id: 4,
        name: "libraries",
      },
      {
        id: 5,
        name: "npm package",
      },
      {
        id: 6,
        name: "JS API",
      },
      {
        id: 7,
        name: "hosting",
      },
      {
        id: 8,
        name: "design",
      },
      {
        id: 9,
        name: "DSA",
      },
    ],
    skill_data: [
      {
        id: 3,
        active: 1,
        rank: 1,
        titleImg: "./assets/skill/node1.png",
        title: "NODE-JS (Backend)",
        subtitle: "Node-Js",
        category: ["backend"],
        points: [
          {
            id: 0,
            img: "./assets/skill/correct2.jpg",
            content: "Good understanding of Syntax",
          },
          {
            id: 1,
            img: "./assets/skill/correct2.jpg",
            content: "Create Servers",
          },
          {
            id: 2,
            img: "./assets/skill/correct2.jpg",
            content: "Routes",
          },
          {
            id: 3,
            img: "./assets/skill/correct2.jpg",
            content: "Fs, Path, Os Modules",
          },
          {
            id: 4,
            img: "./assets/skill/correct2.jpg",
            content: "Connect with Frontend",
          },
          {
            id: 5,
            img: "./assets/skill/correct2.jpg",
            content: "Connect with Database",
          },
          {
            id: 6,
            img: "./assets/skill/correct2.jpg",
            content: "Many more things",
          },
        ],
      },
      {
        id: 4,
        active: 1,
        rank: 2,
        titleImg: "./assets/skill/express.png",
        title: "EXPRESS (Backend)",
        subtitle: "Express",
        category: ["backend", "libraries"],
        points: [
          {
            id: 0,
            img: "./assets/skill/correct2.jpg",
            content: "Good understanding of Syntax",
          },
          {
            id: 1,
            img: "./assets/skill/correct2.jpg",
            content: "Create Servers",
          },
          {
            id: 2,
            img: "./assets/skill/correct2.jpg",
            content: "Routers",
          },
          {
            id: 3,
            img: "./assets/skill/correct2.jpg",
            content: "Intergrate with Various Modules",
          },
          {
            id: 4,
            img: "./assets/skill/correct2.jpg",
            content: "Connect with Frontend",
          },
          {
            id: 5,
            img: "./assets/skill/correct2.jpg",
            content: "Connect with Database",
          },
          {
            id: 6,
            img: "./assets/skill/correct2.jpg",
            content: "GET, POST, PUT, DELETE",
          },
          {
            id: 7,
            img: "./assets/skill/correct2.jpg",
            content: "Many more things",
          },
        ],
      },
      {
        id: 5,
        active: 1,
        rank: 3,
        titleImg: "./assets/skill/mongo.png",
        title: "MONGO Database",
        subtitle: "Mongo-DB",
        category: ["backend", "database"],
        points: [
          {
            id: 0,
            img: "./assets/skill/correct2.jpg",
            content: "Good understanding of Syntax",
          },
          {
            id: 1,
            img: "./assets/skill/correct2.jpg",
            content: "Mongoose Packages",
          },
          {
            id: 2,
            img: "./assets/skill/correct2.jpg",
            content: "Filter, Sorting etc Properties",
          },
          {
            id: 3,
            img: "./assets/skill/correct2.jpg",
            content: "Work on CLI",
          },
          {
            id: 4,
            img: "./assets/skill/correct2.jpg",
            content: "Connect with Frontend",
          },
          {
            id: 5,
            img: "./assets/skill/correct2.jpg",
            content: "Connect with Backend",
          },
          {
            id: 6,
            img: "./assets/skill/correct2.jpg",
            content: "Mongo-DB Atlas",
          },
          {
            id: 7,
            img: "./assets/skill/correct2.jpg",
            content: "Many more things",
          },
        ],
      },
      {
        id: 6,
        active: 1,
        rank: 4,
        titleImg: "./assets/skill/react.png",
        title: "REACT-JS : Frontend",
        subtitle: "React-Js",
        category: ["frontend", "design", "libraries"],
        points: [
          {
            id: 0,
            img: "./assets/skill/correct2.jpg",
            content: "Good understanding of Syntax",
          },
          {
            id: 1,
            img: "./assets/skill/correct2.jpg",
            content: "ES6 propeties",
          },
          {
            id: 2,
            img: "./assets/skill/correct2.jpg",
            content: "Life Cycle of Component",
          },
          {
            id: 3,
            img: "./assets/skill/correct2.jpg",
            content: "Redux Toolkit",
          },
          {
            id: 4,
            img: "./assets/skill/correct2.jpg",
            content: "React Router Dom",
          },
          {
            id: 5,
            img: "./assets/skill/correct2.jpg",
            content: "Context API",
          },
          {
            id: 6,
            img: "./assets/skill/correct2.jpg",
            content: "Hooks",
          },
          {
            id: 7,
            img: "./assets/skill/correct2.jpg",
            content: "Connect with Backend",
          },
          {
            id: 8,
            img: "./assets/skill/correct2.jpg",
            content: "Connect with Database",
          },
          {
            id: 9,
            img: "./assets/skill/correct2.jpg",
            content: "Many more things",
          },
        ],
      },
      {
        id: 7,
        active: 1,
        rank: 5,
        titleImg: "./assets/skill/firebase.png",
        title: "FIREBASE : Database",
        subtitle: "Firebase",
        category: ["frontend", "backend", "database"],
        points: [
          {
            id: 0,
            img: "./assets/skill/correct2.jpg",
            content: "Good understanding of tools",
          },
          {
            id: 1,
            img: "./assets/skill/correct2.jpg",
            content: "Connect with Frontent",
          },
          {
            id: 2,
            img: "./assets/skill/correct2.jpg",
            content: "Authentications",
          },
          {
            id: 3,
            img: "./assets/skill/correct2.jpg",
            content: "Real time database",
          },
          {
            id: 4,
            img: "./assets/skill/correct2.jpg",
            content: "Clud Storage",
          },
          {
            id: 5,
            img: "./assets/skill/correct2.jpg",
            content: "Hosting",
          },
          {
            id: 6,
            img: "./assets/skill/correct2.jpg",
            content: "Many more things",
          },
        ],
      },
      {
        id: 12,
        active: 1,
        rank: 6,
        titleImg: "./assets/skill/dsa.png",
        title: "DATA STRUCTURE & ALGORITHMS",
        subtitle: "DSA",
        category: ["DSA"],
        points: [
          {
            id: 0,
            img: "./assets/skill/correct2.jpg",
            content: "1000+ Questions Solved",
          },
          {
            id: 1,
            img: "./assets/skill/correct2.jpg",
            content: "1500+ Rating on LeetCode",
          },
          {
            id: 2,
            img: "./assets/skill/correct2.jpg",
            content: "All Data structures",
          },
          {
            id: 3,
            img: "./assets/skill/correct2.jpg",
            content: "Famous Algorithms",
          },
          {
            id: 4,
            img: "./assets/skill/correct2.jpg",
            content: "Good Problem Solving Skills",
          },
          {
            id: 5,
            img: "./assets/skill/correct2.jpg",
            content: "Many more things",
          },
        ],
      },
      {
        id: 13,
        active: 1,
        rank: 7,
        titleImg: "./assets/skill/redux.png",
        title: "REDUX",
        subtitle: "Redux",
        category: ["frontend", "npm package"],
        points: [
          {
            id: 0,
            img: "./assets/skill/correct2.jpg",
            content: "Good knowledge of middleware",
          },
          {
            id: 1,
            img: "./assets/skill/correct2.jpg",
            content: "Reducer functions",
          },
          {
            id: 2,
            img: "./assets/skill/correct2.jpg",
            content: "Action types & functions",
          },
          {
            id: 3,
            img: "./assets/skill/correct2.jpg",
            content: "Dispatch method",
          },
          {
            id: 5,
            img: "./assets/skill/correct2.jpg",
            content: "Knowledge of Redux Thunk",
          },
          {
            id: 6,
            img: "./assets/skill/correct2.jpg",
            content: "Many more things",
          },
        ],
      },
      {
        id: 8,
        active: 1,
        rank: 8,
        titleImg: "./assets/skill/figma.png",
        title: "FIGMA : Design",
        subtitle: "Figma",
        category: ["frontend", "design"],
        points: [
          {
            id: 0,
            img: "./assets/skill/correct2.jpg",
            content: "Good understanding of tools",
          },
          {
            id: 1,
            img: "./assets/skill/correct2.jpg",
            content: "Frames",
          },
          {
            id: 2,
            img: "./assets/skill/correct2.jpg",
            content: "Groups",
          },
          {
            id: 3,
            img: "./assets/skill/correct2.jpg",
            content: "Color Combination",
          },
          {
            id: 4,
            img: "./assets/skill/correct2.jpg",
            content: "Widgets",
          },
          {
            id: 5,
            img: "./assets/skill/correct2.jpg",
            content: "Many more things",
          },
        ],
      },
      {
        id: 10,
        active: 1,
        rank: 9,
        titleImg: "./assets/skill/js_api's.png",
        title: "JAVASCRIPT API's",
        subtitle: "Js API's",
        category: ["frontend", "JS API"],
        points: [
          {
            id: 0,
            img: "./assets/skill/correct2.jpg",
            content: "Good understanding of API's",
          },
          {
            id: 1,
            img: "./assets/skill/correct2.jpg",
            content: "Intersection Observer",
          },
          {
            id: 2,
            img: "./assets/skill/correct2.jpg",
            content: "Resize Observer",
          },
          {
            id: 3,
            img: "./assets/skill/correct2.jpg",
            content: "Speech Synthesis",
          },
          {
            id: 4,
            img: "./assets/skill/correct2.jpg",
            content: "Speech Recognition",
          },
          {
            id: 5,
            img: "./assets/skill/correct2.jpg",
            content: "Many more things",
          },
        ],
      },
      {
        id: 0,
        active: 1,
        rank: 10,
        titleImg: "./assets/skill/html.png",
        title: "HTML:Hyper Text Markup Language",
        subtitle: "HTML",
        category: ["frontend"],
        points: [
          {
            id: 0,
            img: "./assets/skill/correct2.jpg",
            content: "Good understanding of all Tags",
          },
          {
            id: 1,
            img: "./assets/skill/correct2.jpg",
            content: "Tricks about SEO",
          },
          {
            id: 2,
            img: "./assets/skill/correct2.jpg",
            content: "Canvas for game development",
          },
          {
            id: 3,
            img: "./assets/skill/correct2.jpg",
            content: "Link with CSS",
          },
          {
            id: 4,
            img: "./assets/skill/correct2.jpg",
            content: "Link with JS",
          },
          {
            id: 5,
            img: "./assets/skill/correct2.jpg",
            content: "Forms and Events",
          },
          {
            id: 6,
            img: "./assets/skill/correct2.jpg",
            content: "Many more things",
          },
        ],
      },
      {
        id: 1,
        active: 1,
        rank: 11,
        titleImg: "./assets/skill/css.png",
        title: "Cascading Style Sheet : CSS",
        subtitle: "CSS",
        category: ["frontend", "design"],
        points: [
          {
            id: 0,
            img: "./assets/skill/correct2.jpg",
            content: "Good understanding all CSS properties",
          },
          {
            id: 1,
            img: "./assets/skill/correct2.jpg",
            content: "Pseudo Elements",
          },
          {
            id: 2,
            img: "./assets/skill/correct2.jpg",
            content: "Flex Box Properties",
          },
          {
            id: 3,
            img: "./assets/skill/correct2.jpg",
            content: "Grid properties",
          },
          {
            id: 4,
            img: "./assets/skill/correct2.jpg",
            content: "Media Propeties",
          },
          {
            id: 5,
            img: "./assets/skill/correct2.jpg",
            content: "Knowledge of @Keyframes",
          },
          {
            id: 6,
            img: "./assets/skill/correct2.jpg",
            content: "--root(), var() & calc() properties",
          },
          {
            id: 7,
            img: "./assets/skill/correct2.jpg",
            content: "::before and ::after class",
          },
          {
            id: 8,
            img: "./assets/skill/correct2.jpg",
            content: "Many more things",
          },
        ],
      },
      {
        id: 2,
        active: 1,
        rank: 12,
        titleImg: "./assets/skill/js.png",
        title: "JavaScript : JS",
        subtitle: "JavaScript",
        category: ["frontend", "Backend"],
        points: [
          {
            id: 0,
            img: "./assets/skill/correct2.jpg",
            content: "Good understanding of Syntax",
          },
          {
            id: 1,
            img: "./assets/skill/correct2.jpg",
            content: "JS API's",
          },
          {
            id: 2,
            img: "./assets/skill/correct2.jpg",
            content: "Understanding of Object and Arrays",
          },
          {
            id: 3,
            img: "./assets/skill/correct2.jpg",
            content: "Async & Await and try & catch",
          },
          {
            id: 4,
            img: "./assets/skill/correct2.jpg",
            content: "Promises, Clousers, bind etc. Properties",
          },
          {
            id: 5,
            img: "./assets/skill/correct2.jpg",
            content: "DOM Properties",
          },
          {
            id: 6,
            img: "./assets/skill/correct2.jpg",
            content: "(Get, Post, Put, Delete) : Fetch",
          },
          {
            id: 7,
            img: "./assets/skill/correct2.jpg",
            content: "Window properties",
          },
          {
            id: 8,
            img: "./assets/skill/correct2.jpg",
            content: "Many more things",
          },
        ],
      },
      {
        id: 9,
        active: 1,
        rank: 13,
        titleImg: "./assets/skill/npm.png",
        title: "NPM PACKAGES",
        subtitle: "NPM",
        category: ["frontend", "backend", "npm package"],
        points: [
          {
            id: 0,
            img: "./assets/skill/correct2.jpg",
            content: "Good understanding of packages",
          },
          {
            id: 1,
            img: "./assets/skill/correct2.jpg",
            content: "Date Module",
          },
          {
            id: 2,
            img: "./assets/skill/correct2.jpg",
            content: "Multer Module",
          },
          {
            id: 3,
            img: "./assets/skill/correct2.jpg",
            content: "CORS Module",
          },
          {
            id: 4,
            img: "./assets/skill/correct2.jpg",
            content: "React Router DOM and Redux",
          },
          {
            id: 5,
            img: "./assets/skill/correct2.jpg",
            content: "Mongoose Module",
          },
          {
            id: 6,
            img: "./assets/skill/correct2.jpg",
            content: "Many more things",
          },
        ],
      },
      {
        id: 11,
        active: 1,
        rank: 14,
        titleImg: "./assets/skill/hosting.png",
        title: "HOSTING : DEPLOY",
        subtitle: "Hosting",
        category: ["frontend", "hosting", "backend"],
        points: [
          {
            id: 0,
            img: "./assets/skill/correct2.jpg",
            content: "Vercel website",
          },
          {
            id: 1,
            img: "./assets/skill/correct2.jpg",
            content: "Netlify website",
          },
          {
            id: 2,
            img: "./assets/skill/correct2.jpg",
            content: "GitHub pages",
          },
          {
            id: 3,
            img: "./assets/skill/correct2.jpg",
            content: "FireBase website",
          },
          {
            id: 4,
            img: "./assets/skill/correct2.jpg",
            content: "Heroku",
          },
          {
            id: 5,
            img: "./assets/skill/correct2.jpg",
            content: "Railway website",
          },
          {
            id: 6,
            img: "./assets/skill/correct2.jpg",
            content: "Many more things",
          },
        ],
      },
    ],
  },
  AboutUsPage: {
    id: 3,
    keywords: {
      heading: "About Us",
    },
    about_data: [
      {
        id: 0,
        imp: false,
        content:
          "I am passionate in the programming and logic building & I am also enjoy building User Experience and Interface",
      },
      {
        id: 1,
        imp: false,
        content:
          "I am Passionate and curious to learn new Technologies & their Applications.",
      },
      {
        id: 2,
        imp: true,
        content: "I am also a Good Problem Solver. 1500+ ratings on LeetCode",
      },
      {
        id: 3,
        imp: false,
        content:
          "I have a Competative thinking which help me to grow fast and learn more & more.",
      },
    ],
  },
};
